import Foundation

struct Network: Identifiable, Hashable {
  let id = UUID()
  var name = ""
  var isSecured = true
  var connectivity = 1.0
}

extension [Network] {
  static let mocks = [
    Network(
      name: "nachos",
      isSecured: true,
      connectivity: 0.5
    ),
    Network(
      name: "nachos 5G",
      isSecured: true,
      connectivity: 0.75
    ),
    Network(
      name: "Blob Jr's LAN PARTY",
      isSecured: true,
      connectivity: 0.2
    ),
    Network(
      name: "Blob's World",
      isSecured: false,
      connectivity: 1
    ),
  ]
}

// TODO: got this list from the internet, remove anything dumb or offensive
let goofyWiFiNames = [
  "AirSpace1",
  "Living Room",
  "Courage",
  "Nacho WiFi",
  "FBI Surveillance Van",
  "Peacock-Swagger",
  "GingerGymnist",
  "Second Floor",
  "Evergreen",
  "__hidden_in_plain__sight__",
  "MarketingDropBox",
  "HamiltonVille",
  "404NotFound",
  "SNAGVille",
  "Overland101",
  "TheRoomWiFi",
  "PrivateSpace",
  "$12.99/hr WIFI",
  "Drop It Like Its Hotspot",
  "Keep It On The Download",
  "Panic At The Cisco",
  "Bill Wi the Science Fi",
  "Hogwarts Hall of Wifi",
  "The Force",
  "Chance the Router",
  "Wu-Tang LAN",
  "Wi-Fight the Feeling",
  "A LANister Never Forgets",
  "May the Wi-Force Be With You",
  "Inigo the Modem",
  "Formerly Known as Prints",
  "Wi-Fight the Inevitable",
  "IanTernet",
  "Winternet is Coming",
  "Common Room Wifi",
  "Jar Jar Linksys",
  "Art Vandelay",
  "The Password is...",
  "House LANister",
  "Yer A Wifi Harry",
  "These Are Not the Droids You’re Looking For",
  "Never Gonna Give You Wifi",
  "H.E. Pennypacker",
  "Abraham Linksys",
  "Open Sesame",
  "For Whom the Belkin Tolls",
  "LANnisters Pay Their Debts",
  "Hagrid’s Hut",
  "A Long Time Ago…",
  "Chance the Router",
  "Silence of the LAN",
  "Every Day I’m Buffering",
  "RIP Net Neutrality",
  "LANnisters Send Their Regards",
  "Accio Internet",
  "MothersMaidenName",
  "John Wilkes Bluetooth",
  "Bandwidth Together",
  "Who What When Where WiFi",
  "You Shall Not Password",
  "Dumbledore's IT Staff",
  "I am WAN with the Web and the Web is with Me",
  "Password is Password",
  "Benjamin FrankLAN",
  "Lag Out Loud",
  "Wi Fi Fo Fum",
  "The Ping of the North",
  "Connecto Patronum",
  "Luke, I Am Your Wi-Fi",
  "Password is Gullible",
  "Alexander Graham Belkin",
  "No More Mister Wifi",
  "Hit the Road Jack Input",
  "And Don’t You Come Back",
  "No Mo No Mo No Mo No Mo",
  "JackPott",
  "The Mad Ping",
  "Squibs Only",
  "Forest Moon of Endor",
  "Theodore Routervelt",
  "No LAN for the Wicked",
  "Blind Sight",
  "Printer Only",
  "House of Black and Wifi",
  "Floo Network",
  "Docking Bay 94",
  "The LAN Down Under",
  "Franklin Delano Routervelt",
  "I Believe Wi Can Fi",
  "Daily Bread",
  "Comcasterly Rock",
  "Spread the Wealth",
  "Where the Wild Pings Are",
  "Now You See Me…",
  "Searching…",
  "Lord of the Ping",
  "Pretty Fly for a WiFi",
  "New England Clam Router",
  "Sweet Victory",
  "One if by LAN…",
  "One Wifi to Rule Them All",
  "Linksys Lohan",
  "Go Go Router Rangers",
  "Life on the Line",
  "AAAAAAAAAA",
  "Routers of Rohan",
  "Enter the Dragon’s Wifi",
  "Winona Router",
  "IP Steady Streams",
  "Cut the Wire",
  "Huge Tracts of LAN",
  "You Click, I Pay",
  "John Claude WAN Damme",
  "The Promised LAN",
  "FBI Channel 90210",
  "The Black Links",
  "Ludwig WAN Beethoven",
  "PorqueFi",
  "Since 1997",
  "FBI Van 13",
  "404 Network Unavailable",
  "Try Me",
  "Abraham WAN Helsing",
  "The LAN Before Time",
  "Surveillance Van",
  "Alt-255",
  "Full Bars",
  "LAN Halen",
  "Scooby-Doo, Where Are You?",
  "Witness Protection",
  "LAN Morrison",
  "LAN of Milk and Honey",
  "Final Fantasy Finally Finishes",
  "Tell My Wifi Love Her",
  "Unregistered Hypercam 2",
  "Bilbo Laggins",
  "The LAN of the Free",
  "Saved a Bunch of Money by Switching to GEICO",
  "It’s a Small World Wifi Internet",
  "Spiderman’s World Wide Web",
  "Do Re Mi Fa So La Wi Fi",
  "Lord Voldemodem",
  "Wifi Art Thou Romeo",
]
